name: Deploy to Prod

on:
  push:
    branches:
      - prod

env:
  REGION: ${{ secrets.REGION }}
  PROD_GCP_IMAGE: seva-next
  PROD_GCP_PROJECT: ${{ secrets.PROD_GCP_PROJECT }}

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v2
      - name: Prepare Environment Variable
        run: |
          echo "CI=false" >> .env
          echo "PUBLIC_URL=${{ secrets.PROD_PUBLIC_URL }}" >> .env
          echo "NODE_ENV=production" >> .env
          echo "NEXT_PUBLIC_LOCAL_STORAGE_ENCRYPTION_KEY=${{ secrets.LOCAL_STORAGE_ENCRYPTION_KEY }}" >> .env
          echo "NEXT_PUBLIC_LEAD_PAYLOAD_ENCRYPTION_KEY=${{ secrets.LEAD_PAYLOAD_ENCRYPTION_KEY }}" >> .env
          echo "NEXT_PUBLIC_SERVER_BASE_URL=${{secrets.PROD_PUBLIC_URL}}" >> .env
          echo "NEXT_PUBLIC_FIREBASE_API_KEY=${{secrets.PROD_REACT_FIREBASE_API_KEY}}" >> .env
          echo "NEXT_PUBLIC_ENVIRONMENT=production" >> .env

      - name: Auth Cloud SDK
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.PROD_SERVICE_ACCOUNT_KEY }}'

      - name: Deploy Image to Google Container Registry
        run: |
          gcloud builds submit --timeout=1800s\
            --tag gcr.io/$PROD_GCP_PROJECT/$PROD_GCP_IMAGE \
            --gcs-log-dir gs://torq-build-logs-prod/container

      - name: Update Cloud Run with latest Container Image
        run: |
          gcloud run deploy $PROD_GCP_IMAGE \
            --region $REGION \
            --image gcr.io/$PROD_GCP_PROJECT/$PROD_GCP_IMAGE \
            --platform managed \
            --allow-unauthenticated \
            --min-instances 1 \
            --max-instances 20 \
            --concurrency 80 \
            --cpu 1 \
            --memory 1024Mi
